version: '3'
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  ng:
    ports:
     - "8888:8888"
    build:
      context: .
      dockerfile: Dockerfile
    links:
     - "redis"
    environment:
      - REDIS_HOST=redis
